---
- name: update apt cache
  apt:
    update_cache: yes
  tags: 
    - install_rbenv
    - install_ruby_build

- name: Install dependencies for rbenv (Debian)
  apt: 
    pkg: "{{ item }}" 
  with_items:
    - git
    - autoconf
    - bison
    - build-essential
    - libssl-dev
    - libyaml-dev
    - libreadline-dev
    - libffi-dev
    - zlib1g
    - zlib1g-dev
  tags: 
    - install_rbenv
    - install_ruby_build