---
- include: Debian.yml
  when: ansible_os_family == "Debian"

- name: Install rbenv
  become: yes
  become_user: "{{ item.username }}"
  git: 
    repo: git://github.com/sstephenson/rbenv.git 
    dest: "~/.rbenv"
    accept_hostkey: yes 
    version: "{{ item.rbenv_version | default('HEAD') }}"
  with_items:
    - "{{ rbenv_users }}"
  when:
    - rbenv_users is defined
  tags: 
    - install_rbenv
    - install_ruby_build

- name: Install rbenv.sh
  template:
    src: etc/profile.d/rbenv.sh.j2
    dest: /etc/profile.d/rbenv.sh
  tags: 
    - install_rbenv
    - install_ruby_build

- name: Copy .gemrc to ~/.gemrc
  become: yes
  become_user: "{{ item.username }}"
  copy:
    src: .gemrc 
    dest: "{{ lookup('env','HOME') }}/.gemrc"
  with_items:
    - "{{ rbenv_users }}"
  when:
    - rbenv_users is defined
  tags: install_rbenv

- name: Install ruby-build as rbenv plugin
  become: yes
  become_user: "{{ item.username }}"
  git: 
    repo: https://github.com/sstephenson/ruby-build.git 
    dest: ~/.rbenv/plugins/ruby-build
  with_items:
    - "{{ rbenv_users }}"
  when:
    - rbenv_users is defined
  tags: 
    - install_rbenv
    - install_ruby_build

- name: "Install {{item.1.version }}"
  become: yes
  become_method: sudo
  become_user: "{{ item.0.username }}"
  command: "rbenv install -s {{ item.1.version }}"
  environment:
     PATH: "{{ lookup('env','HOME') }}/.rbenv/bin:{{ lookup('env','PATH') }}"
  with_subelements:
    - rbenv_users
    - ruby_versions
  tags: install_ruby
  when:
    - rbenv_users is defined 
    - item.1.state == 'present'

- name: "uninstall ruby version {{item.1.version }}"
  become: yes
  become_method: sudo
  become_user: "{{ item.0.username }}"
  command: "rbenv uninstall -f {{ item.1.version }}"
  environment:
     PATH: "{{ lookup('env','HOME') }}/.rbenv/bin:{{ lookup('env','PATH') }}"
  with_subelements:
    - rbenv_users
    - ruby_versions
  tags: remove_ruby
  when:
    - rbenv_users is defined 
    - item.1.state == 'absent'

- name: "set default ruby version {{item.1.version }}"
  become: yes
  become_method: sudo
  become_user: "{{ item.0.username }}"
  command: "rbenv global {{ item.1.version }}"
  environment:
     PATH: "{{ lookup('env','HOME') }}/.rbenv/bin:{{ lookup('env','PATH') }}"
  with_subelements:
    - rbenv_users
    - ruby_versions
  tags: install_ruby
  when:
    - rbenv_users is defined
    - item.1.default is defined
    - item.1.default

- name: install bundler
  become: yes
  become_method: sudo
  become_user: "{{ item.0.username }}"
  command: "rbenv exec gem install bundler"
  environment:
     PATH: "{{ lookup('env','HOME') }}/.rbenv/bin:{{ lookup('env','PATH') }}"
     RUBY_VERSION: "{{item.1.version }}"
  with_subelements:
    - rbenv_users
    - ruby_versions
  tags:
      - install_ruby
      - install_bundler
  when:
    - rbenv_users is defined 
    - item.1.state == 'present'
