---
- name: update apt cache
  apt:
    update_cache: yes
  tags: [install_rbenv,install_ruby_build]

- name: Install dependencies for rbenv
  apt: 
    pkg: git
  tags: install_rbenv

- name: Install rbenv
  sudo: yes
  sudo_user: "{{ rbenv.user }}"
  git: 
    repo: git://github.com/sstephenson/rbenv.git 
    dest: "~/.rbenv"
    accept_hostkey: yes 
    version: "{{ rbenv.version | default('HEAD') }}"
  tags: install_rbenv

- name: Add ~.rbenv/bin to PATH
  sudo: yes
  sudo_user: "{{ rbenv.user }}"
  lineinfile: >
    dest="~/.profile"
    line="export PATH=$HOME/.rbenv/bin:$PATH"
  tags: install_rbenv

- name: Eval rbenv init in ~/.profile
  sudo: yes
  sudo_user: "{{ rbenv.user }}"
  lineinfile: >
    dest="~/.profile"
    line='eval "$(rbenv init -)"'
  tags: install_rbenv

- name: Copy .gemrc to ~/.gemrc
  sudo: yes
  sudo_user: "{{ rbenv.user }}"
  copy: src={{ item }} dest=~/.gemrc
  with_first_found:
    - ../../../files/.gemrc
    - .gemrc
  tags: install_rbenv

- name: Install dependencies for ruby-build
  apt: pkg={{ item }}
  with_items:
    - autoconf
    - bison
    - build-essential
    - libssl-dev
    - libyaml-dev
    - libreadline-dev
    - libffi-dev
    - zlib1g
    - zlib1g-dev
  tags: install_ruby_build

- name: Install ruby-build as rbenv plugin
  sudo: yes
  sudo_user: "{{ rbenv.user }}"
  git: 
    repo: https://github.com/sstephenson/ruby-build.git 
    dest: ~/.rbenv/plugins/ruby-build
  tags: install_ruby_build

- name: Check if requirement ruby version is installed
  shell: "sudo -iu {{ rbenv.user }} rbenv versions | grep {{ rbenv.ruby_version }}"
  register: rbenv_check_install
  changed_when: False
  ignore_errors: True
  tags: install_ruby

- name: "Install {{ rbenv.ruby_version }}"
  command: "sudo -iu {{ rbenv.user }} rbenv install {{ rbenv.ruby_version }}"
  when: rbenv_check_install|failed
  tags: install_ruby

- name: "Check if {{ rbenv.ruby_version }} is the default ruby version"
  shell: "sudo -iu {{ rbenv.user }} rbenv version | grep {{ rbenv.ruby_version }}"
  register: rbenv_check_default
  changed_when: False
  ignore_errors: True
  tags: install_ruby

- name: "Set default ruby version to {{ rbenv.ruby_version }}"
  shell: "sudo -iu {{ rbenv.user }} rbenv global {{ rbenv.ruby_version }}"
  when: rbenv_check_default|failed
  tags: install_ruby

- name: install bundler
  shell: 'sudo -iu {{ rbenv.user }} rbenv exec gem list -i bundler'
  register: gem_bundler
  changed_when: False
  ignore_errors: True

- name: install bundler
  shell: "sudo -iu {{ rbenv.user }} rbenv exec gem install bundler"
  when: "'false' in gem_bundler.stdout"

